server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pollsDB?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: test
    password: 12345678
    initialization-mode: always
  jpa:
    properties:
      hiberante:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
