server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pollsDB?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: demo
    password: demo
    initialization-mode: always
  jpa:
    properties:
      hiberante:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

app.jwtSecret: JWTSupersecretKey
app.jwtExpirationInMs: 60480000

logging.level.org.springframework.web: TRACE
