server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pollsDB?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: demo
    password: demo
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hiberante:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 420049322251-vgc4ink683hac89vsktgqirgkisnc7sn.apps.googleusercontent.com
            clientSecret: LkBnlq4x4igZjyZumbYDop0f
            redirectUriTemplate: "{baseUrl}/api/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG


app:
  auth:
    jwtSecret: JWTSupersecretKey
    jwtExpirationInMs: 60480000
  oauth2:
    authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
    - myandroidapp://oauth2/redirect
    - myiosapp://oauth2/redirect

logging.level.org.springframework.web: TRACE
